name: Run Selenium Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager

    - name: Run Selenium script
      run: python esim_holafly.py

    - name: Commit CSV output to repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add product_data.csv
        git commit -m "Add latest product_data.csv [skip ci]" || echo "No changes to commit"

    - name: Push changes
      run: git push
